<?php

use Drupal\Core\Render\Markup;

/**
 * Implements hook_theme_registry_alter
 */
function msn_feed_theme_registry_alter(&$theme_registry) {
  $theme_registry['paragraph__video_youtube__feed']['template'] = 'paragraph--video-youtube--feed';
  $theme_registry['paragraph__video_youtube__feed']['path'] = drupal_get_path('module', 'msn_feed') . '/templates';
  $theme_registry['paragraph__video_youtube__feed']['type'] = 'base_theme_engine';

  $theme_registry['views_view_row_rss']['path'] = drupal_get_path('module', 'msn_feed') . '/templates';
}

/**
 * Implements template_preprocess_views_view_row_rss
 */
function msn_feed_preprocess_views_view_row_rss(&$vars) {
  $item = $vars['row'];
  $vars['content'] = $item->content;
  $vars['teaser_text'] = $item->teaser_text;
  $vars['teaser_image'] = $item->teaser_image;
}

/**
 * Paragraphs - Gallery item
 * @param $variables
 */
function msn_feed_preprocess_paragraph(&$vars) {
  $paragraph = $vars['paragraph'];
  $bundle = $paragraph->bundle();
  if ($bundle == 'video' && $vars['view_mode'] == 'feed') {
    //deal with video upload
    //dpm($vars,'video vars');
    // dpm($paragraph,'par');
    //dpm($paragraph->get('field_video'), 'video');
    //dpm($paragraph->get('field_file')->entity, 'file video');
  }

  if ($bundle == 'image' && $vars['view_mode'] == 'feed') {
    $content = msn_feed_format_image($paragraph->get('field_image')->entity); //media entity
    $vars['content'] = $content;
  }
}

/**
 * formats image for msn feed
 * @param Drupal\media_entity\Entity\Media media_entity
 * @return Drupal\Core\Render\Markup
 */
function msn_feed_format_image($media_entity) {

  if(!$media_entity) {
    return array();
  }
  $copyright = $media_entity->get('field_copyright')->value;
  if(!$copyright) {
    $copyright = '&copy; Burda Praha';
  }
  $image_field = $media_entity->get('field_image');
  $image_file = $image_field->entity;
  $image_uri = $image_file->getFileUri();
  $image_info = $image_field->getValue();
  $image_info = reset($image_info);
  $default_alt = "Burda Praha";
  if(!$image_info['alt']) {
    $image_info['alt'] = $default_alt;
  }
  if(!$image_info['title']) {
    $image_info['title'] = $default_alt;
  }
  $image_url = file_create_url($image_uri);
  /*
  $image_render_array = [
    '#theme' => 'image_style',
    '#style_name' => 'feed',
    '#uri' => $image_uri,
    '#alt' => $image_info['alt'],
    '#title' => $image_info['title'],
    '#attributes' => ['data-portal-copyright' => $copyright]
 ];
 */
 //image style outputs relative image path and we need absolute url so screw it
 $markup = '<img
   src="' . $image_url . '"
   alt="' . $image_info['alt'] .'"
   title = "' . $image_info['title'] . '"
   data-portal-copyright = "' . $copyright . '" />';
   $output = Markup::create($markup);
 return $output;
}
